maintenanceModeOnStart: false
remainingMilliseconds: 0
kickMessage: "\xa7c\xa7nThe server is currently under maintenance. Come back later."
maintenanceMessage: "\xa7c\xa7nThe server is currently under maintenance. Come back\
  \ later."
maintenanceMOTD: "\xa76\xa7o\xa7lMaintenance mode..."
maintenanceWithDurationMOTDBegin: "\xa76\xa7o\xa7lMaintenance mode...\xa72\xa7l"
maintenanceWithDurationMOTDEnd: "\xa7r\xa7eminutes remaining!"
maintenanceWithDurationMOTDLessThanOneMinute: "\xa72Less than one minute remaining!"
maintenanceStart: "\xa72\xa7o\xa7lMaintenance time!"
maintenanceEnd: "\xa76\xa7o\xa7lMaintenance finished!"
scheduleMessageBegin: "\xa75\xa7oMaintenance in\xa7r\xa74\xa7l"
scheduleMessageEnd: "\xa7r\xa75\xa7ominutes!"
scheduleCanceled: "\xa7a\xa7oThe scheduled maintenance have been canceled!"
noMaintenanceScheduled: "\xa7cNo maintenance scheduled..."
scheduleLessThanOneMinute: "\xa75\xa7oMaintenance in less than one minute!"
inputErrorSchedule: "\xa7cThe time value for schedule must be an integer!"
inputErrorDuration: "\xa7cThe time value for duration must be an integer!"
pluginManagementArgumentErrorDisable: "\xa7cPlease name the plugin you want to disable!"
pluginManagementArgumentErrorEnable: "\xa7cPlease name the plugin you want to enable!"
pluginDisabled: "\xa7a\xa7osuccessfully disabled!"
pluginEnabled: "\xa7a\xa7osuccessfully enabled!"
maintenanceAlreadyLaunched: "\xa7cThe server is already in maintenance mode."
noMaintenanceLaunched: "\xa7cMaintenance mode is already off."
maintenanceAlreadyScheduled: "\xa7cA maintenance is already scheduled."
loginMessage: "\xa76\xa7o\xa7lThe server is currently in maintenance mode!"
cpuUsage: "\xa73CPU used at\xa72\xa7l"
ramUsage: "\xa73RAM used at\xa72\xa7l"
maxPlayersOnMaintenance: 10
disabledPlugins: []
