name: MaintenanceManager
main: io.github.jeremgamer.maintenance.Maintenance
version: 0.2
commands:
   maintenance:
      description: All commands from MaintenanceManager
      usage: /maintenance [on|off|reload|enable|disable] (schedule in minutes|plugin name) <duration in minutes>
      permission: maintenance.*
      permission-message: You are not allowed to do that.

