name: Maintenance
main: io.github.jeremgamer.maintenance.Maintenance
version: 0.0.1-SNAPSHOT
commands:
   maintenance:
      description: Turn on or off the maintenance time. You can schedule the maintenance and its duration.
      usage: /maintenance [on|off] (schedule in minutes) <duration in minutes>
      permission: maintenance.maintenance
      permission-message: You are not allowed to do that.

